services:
  nextcloud-aio-mastercontainer:
    image: 'nextcloud/all-in-one:latest'
    restart: always
    container_name: nextcloud-aio-mastercontainer
    init: true
    volumes:
      - 'nextcloud_aio_mastercontainer:/mnt/docker-aio-config'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    ports:
      - '11001:8080' 
    environment:
      - APACHE_PORT: 11000
      - APACHE_IP_BINDING: 0.0.0.0
      - SKIP_DOMAIN_VALIDATION: true
      - NEXTCLOUD_MEMORY_LIMIT: ${NEXTCLOUD_MEMORY_LIMIT:-1024M}
      - NEXTCLOUD_MOUNT: /mnt/
      
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

